// Code generated by MockGen. DO NOT EDIT.
// Source: public-api/service (interfaces: ListingService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "public-api/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockListingService is a mock of ListingService interface.
type MockListingService struct {
	ctrl     *gomock.Controller
	recorder *MockListingServiceMockRecorder
}

// MockListingServiceMockRecorder is the mock recorder for MockListingService.
type MockListingServiceMockRecorder struct {
	mock *MockListingService
}

// NewMockListingService creates a new mock instance.
func NewMockListingService(ctrl *gomock.Controller) *MockListingService {
	mock := &MockListingService{ctrl: ctrl}
	mock.recorder = &MockListingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListingService) EXPECT() *MockListingServiceMockRecorder {
	return m.recorder
}

// CreateListing mocks base method.
func (m *MockListingService) CreateListing(arg0 context.Context, arg1 model.Listing) (*model.Listing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateListing", arg0, arg1)
	ret0, _ := ret[0].(*model.Listing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateListing indicates an expected call of CreateListing.
func (mr *MockListingServiceMockRecorder) CreateListing(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateListing", reflect.TypeOf((*MockListingService)(nil).CreateListing), arg0, arg1)
}

// GetListings mocks base method.
func (m *MockListingService) GetListings(arg0 context.Context, arg1, arg2 int, arg3 *int64) ([]model.Listing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListings", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]model.Listing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListings indicates an expected call of GetListings.
func (mr *MockListingServiceMockRecorder) GetListings(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListings", reflect.TypeOf((*MockListingService)(nil).GetListings), arg0, arg1, arg2, arg3)
}
